name: Test SigHUP

on:
  push:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: Invoke
      shell: bash
      run: |
        trap 'echo "Trapped signal 0"' 0
        trap 'echo "Trapped signal 1"' 1
        trap 'echo "Trapped signal 2"' 2
        trap 'echo "Trapped signal 3"' 3
        sleep 120
